### ISSUE TITLE
[CW-2099] Can't create FB Inbox - Stuck in Empty Page dropdown in step 2

### ISSUE THREAD

**Issue by iamdagy** [chatwoot/chatwoot#7269]
### Describe the bug

I set up my fb app, and star creating the messenger inbox.
after login in to fb and choosing fb and instagram pages, it takes me to step 2 to select the page for the inbox. but the dropdown list is empty.
does anyone know why the dropdown list for page is empty??
Im stuck in this step. any ideas Would be awesome.

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/5bcdfca7-eee5-4446-9ca8-1a5b55267711/3b1dc4a0-58a7-42de-b6ed-e640c65f4423)

in console I see this error showing up :
You are overriding current access token, that means some other app is expecting different access token and you will probably break things. Please consider passing access_token directly to API parameters instead of overriding the global settings. sdk.js?hash=6a6b333efddf4e8a974481afe9d29b3a
and in the container logs I see:
\[2023-06-08T02:06:19.988579 #1\]  INFO -- : \[844c31b5-4ada-4fc8-b0c4-c3fe1e3c55
b4\] Started POST "/api/v1/accounts/1/callbacks/facebook_pages.json" for 181.33.15
9\.218 at 2023-06-08 02:06:19 +0000
I, \[2023-06-08T02:06:19.992912 #1\]  INFO -- : \[844c31b5-4ada-4fc8-b0c4-c3fe1e3c55
b4\] Processing by Api::V1::Accounts::CallbacksController#facebook_pages as JSON
I, \[2023-06-08T02:06:19.993060 #1\]  INFO -- : \[844c31b5-4ada-4fc8-b0c4-c3fe1e3c55
b4\]   Parameters: {"omniauth_token"=>"\[FILTERED\]", "account_id"=>"1", "callback"=

> {"omniauth_token"=>"\[FILTERED\]"}}
> I, \[2023-06-08T02:06:21.639487 #1\]  INFO -- : \[844c31b5-4ada-4fc8-b0c4-c3fe1e3c55
> b4\]   Rendered api/v1/accounts/callbacks/facebook_pages.json.jbuilder (Duration:
> 0\.3ms | Allocations: 54)
> I, \[2023-06-08T02:06:21.643783 #1\]  INFO -- : \[844c31b5-4ada-4fc8-b0c4-c3fe1e3c55
> b4\] Completed 200 OK in 1651ms (Views: 1.4ms | ActiveRecord: 1.9ms | Allocations:

1. 

I, \[2023-06-08T02:06:21.645228 #1\]  INFO -- : source=rack-timeout id=844c31b5-4ad
a-4fc8-b0c4-c3fe1e3c55b4 timeout=15000ms service=1658ms state=completed

### To Reproduce

Im self hosting with docker.
I go to create new inbox, select messenger, login to fb, select fb page and ig page, im taken to step 2. there im stuck.

### Expected behavior

not sure because its the first time setting up fb inbox but surely it should let me advanced.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

docker

### Browser and version

tried safari and chrome

### Docker (if applicable)

Client:
Version:           20.10.23
API version:       1.41
Go version:        go1.19.1
Git commit:        876964a
Built:             Mon May 29 09:43:21 2023
OS/Arch:           linux/amd64
Context:           default
Experimental:      true

Server:
Engine:
Version:          20.10.23
API version:      1.41 (minimum version 1.12)
Go version:       go1.19.1
Git commit:       5fcb1cf
Built:            Mon May 29 09:40:38 2023
OS/Arch:          linux/amd64
Experimental:     false

### Additional context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2099](https://linear.app/chatwoot/issue/CW-2099/cant-create-fb-inbox-stuck-in-empty-page-dropdown-in-step-2)</sub>

**Comment by vishnu-narayanan** [comment]
@iamdagy Have you completed the Facebook app setup and app review process? 

ref: https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup

**Comment by iamdagy** [comment]
I have indeed followed the Facebook app setup guide, however I haven't made the request for app review yet **because** the inbox is not set up yet, so I nor the reviere will be able to test the app. and I think that if they are not able to test it, they don't approve the permissions. 
Also I have a doubt, if the inbox is only for an instagram and Facebook page that I own do I still need the advanced permissions? I thought it was only for when one is using the technology with multiple accounts on behalf of other businesses .
I am reading correctly the docs? ( https://developers.facebook.com/docs/graph-api/overview/access-levels/ ) 
"If your app will only be used by people who have a role on it, the permissions and features your app requires will only need Standard Access. If your app will be used by people who do not have a role on it, the permissions and features that your app requires will need Advanced Access."

**Comment by tejaswinichile** [comment]
@iamdagy If your current Facebook should be in development mode, then Facebook allows you to send webhook events for the test app. And you should add your FB page in Messenger and Instagram settings.

You can test this thing on your local too. https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup/#developing-or-testing-facebook-integration-in-your-machine

If you have set up your app correctly, you can send the test webhook events to the endpoint from this page.

<img width="582" alt="Screenshot 2023-06-09 at 1 18 33 PM" src="https://github.com/chatwoot/chatwoot/assets/10827585/6cb5a936-7327-4a85-a401-b8074ec61418">

**Comment by iamdagy** [comment]
i tiren in development mode and it didn't work either. It seems that there is a change in Facebook login sdk, it is now preferring something called **facebook-login-for-business** :
https://developers.facebook.com/docs/facebook-login/facebook-login-for-business/ 

is this new **facebook-login-for-business**  making this easier or harder for us to integrate messenger and instagram channels? please let me know recommended path

**Comment by chrisedington** [comment]
Also having this issue

**Comment by tejaswinichile** [comment]
@iamdagy facebook-login-for-business is newly introduced by FB.
Can you try if you could switch back to Facebook login https://developers.facebook.com/docs/facebook-login/facebook-login-for-business/#switch_fb_login

**Comment by iamdagy** [comment]
I went back to Facebook login, but nothing seems to work... I have followed the guide, tried with the app in development and production mode, but nothing seems to work.. the Facebook page is not showing in second step of the wizard.

**Comment by iamdagy** [comment]
Following Jordans advice, I selected all pages in the popup and not just the one I wanted and now there is data in the dropdown, but it is not showing the page I want to integrate.. how come? what could that be happening ?

**Comment by iamdagy** [comment]
Hi Team @vishnu-narayanan @tejaswinichile ,

I still think it has something to do with my page being the **New Facebook Page Experience**, im reading that it has a new api and a **specific page tokens**. can anyone help me confirm if this may be the issue, or which direction to troubleshoot. THX

when checking the network tab while trying to create the Facebook inbox I see that:
/api/v1/accounts/1/callbacks/facebook_pages.json --> only shows 1 page that is not new page experience.

on Facebook developer community I found a link to **The API docs** for the New Page Experience:
https://developers.facebook.com/docs/pages/new-pages-experience/overview#new-pages-experience-api-overview

**Comment by jaisonveneri** [comment]
Hello @iamdagy 

I am having the same problem. My facebook pages does not show in the page list when I try to connect them. With other account in the team the pages appeared. I think that you suggestion about new page experience makes sense.

Did you manage to solve this problem?

**Comment by iamdagy** [comment]
@jaisonveneri  Well I was Abel to do it but in hack kind of way. 
1) I added one old experience page
2) I went to the postgress DB in the channel_facebook_page table
3) I change the page_id and user_access_token of the old experience page with desired new experience page data
4) and that was it. It started working. it seems like a chatwoot issue but not sure how to fix it permanently.

**Comment by jaison-x** [comment]
> 

Perfect. Thanks for the heelp @iamdagy

**Comment by mredodos** [comment]
i had same problem how can solve ?

**Comment by mredodos** [comment]
ok i have change something and now work. 

try to go in the page and switch as profile page, go to settings -> new experience page -> advanced messages, here  make sure domains are set up in the whitelist (put subdomain and main domain) and your app is connected to the page

**Comment by mredodos** [comment]
not work again @sojan-official 

I had found this in chrome console

>  You are overriding current access token, that means some other app is expecting different access token and you will probably break things. Please consider passing access_token directly to API parameters instead of overriding the global settings.

**Comment by mredodos** [comment]
ok try to add one page at a time instead of selecting multiple pages(after you had made what i write in previously post)

with one page at time the list not appear empty at my end. 

now i can receive message but not send.

**Comment by pedrofnts** [comment]
@iamdagy how i can get these infos from page?

**Comment by pedrofnts** [comment]
Just updated page_access_token with the one from Facebook app page and page_id. Now I can send and receive messages to my conversation, but my name stays as "John Doe"and I can't receive messages from others (my conversation started with the old page).

**Comment by mredodos** [comment]
If You use caprover try to add the ENV variable to the worker AND to the web

**Comment by nsandau** [comment]
I have the same issue. I have followed the instructions as specified here: [https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup](https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup), but I still get "List is empty". 

Any help would really be appreciated!

**Comment by mredodos** [comment]
> I have the same issue. I have followed the instructions as specified here: https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup, but I still get "List is empty".
> 
> Any help would really be appreciated!
have you add white list domain in all the page?

**Comment by nsandau** [comment]
Yes, as per your suggestion earlier I added both the main domain and the subdomain that we use for chatwoot. But I still get an empty list

**Comment by mredodos** [comment]
> Yes, as per your suggestion earlier I added both the main domain and the subdomain that we use for chatwoot. But I still get an empty list

Are you using caprover?

**Comment by nsandau** [comment]
Thank you for trying to help me solve this. 

No, I do not use caprover.

**Comment by pedrofnts** [comment]
Any news on this?

**Comment by shivamkb17** [comment]
Already this bug is fixed in latest release.

**Comment by pierrecorsini** [comment]
> Already this bug is fixed in latest release.

I dont know if this message refers to `You are overriding current access token, that means some other app is expecting different access token and you will probably break things. Please consider passing access_token directly to API parameters instead of overriding the global settings.`.

But I just updated to v3.3.1 (latest cwctl --upgrade) and the issue is still here.

This seems to happen for me when you try to change the Facebook app linked to chatwoot.

**Comment by gregdotelphotography** [comment]
I am facing the same issue on 3.5.2 running on docker. When trying to pick an Instagram account the list shows empty.

Console message: You are overriding current access token, that means some other app is expecting different access token and you will probably break things. Please consider passing access_token directly to API parameters instead of overriding the global settings.

**Comment by gregdotelphotography** [comment]
After lots of testing I can confirm that because of the new page experience from Facebook, messages from Pages and Instagram will be receive into the same inbox, but will appear separate for each channel in "Conversations".

**Comment by syildiz** [comment]
This problem still persists. I was able to connect my Instagram page in version 3.5.0, but I cannot connect it in version 3.5.2. My Facebook page is connecting, but an empty list is returned for Instagram.

I created an account on Chatwoot and tried to connect it. I couldn't connect there either. Instagram always returns empty.

Is this problem caused by me? Or did something change in the last update?

**Comment by sojan-official** [comment]
closing as there hasn't been recent activity on this issue. We will reopen this if the issue occurs for anyone
