### ISSUE TITLE
fix: Handle instagram direct message images using CDN url

### ISSUE THREAD

**Issue by pelucapampa** [chatwoot/chatwoot#8512]
### Describe the bug

I'm on facebook approval process and we passed History Image CDN URL process OK.
Now, facebook says if messege on Instagram Direct, is an image, we need to use Instagram CDN format (A valid CDN URL sample would be https://lookaside.fbsbx.com/ig_messaging_cdn/?asset_id...
)
I check that on my self hosted installation and chatwoot use an internal URL.
![image](https://github.com/chatwoot/chatwoot/assets/120580431/a04c4e18-0942-49ca-9d9a-b3931c91643c)

When I delete the message on Instagram, chatwoot show "This message was deleted", but not delete the image on conversation.

![image](https://github.com/chatwoot/chatwoot/assets/120580431/03226b71-ee47-4972-af18-fa93c0036305)

It's possible change that on code to use the same CDN URL on image, and delete the image for conversation when user deleted on instagram? (Similar Hisstory image functionallity) for obtain finally instagram_manage_message approve?

### To Reproduce

1: Login into Instagram, search your account, go to message and send an image message
2: Back to chatwoot, open DevOptions and check de URL for the image.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by thelosergeek** [comment]
is this resolved now?

**Comment by pelucapampa** [comment]
Not yet!

**Comment by pelucapampa** [comment]
Hi @pranavrajs, Do you have any idea if it is possible to resolve this, how was the Instagram story resolved?
Thanks. We are waiting to resolve this issue to request facebook approval for instagram and then we make a Go Live for Chatwoot.

**Comment by egejo** [comment]
Hello @pranavrajs please add some priority for the fix, story issues CDN solved on v3.4.0 but I also confirm the issue on image messages. Still can't get advance Instagram permits here too.

**Comment by pelucapampa** [comment]
Hello all.
Could you add Priority to this issue. It's important to Facebook Approval Team to asign advance instagram permissions.
Thanks a lot.

**Comment by jmelati** [comment]
Hi!
Please can you add Priority on this? Same problem here. Thanks!

**Comment by sojan-official** [comment]
Hi all. This requirement has been added after our last audit of the integration. We are looking into this.

**Comment by pelucapampa** [comment]
Thanks @sojan-official

**Comment by DenisKarlyuk** [comment]
Hi all. For those who can't wait:
Got to -> `app/models/attachment.rd`
change
`metadata[:data_url] = metadata[:thumb_url] = external_url if message.instagram_story_mention?`
to
`metadata[:data_url] = metadata[:thumb_url] = external_url if message.instagram?`
![image](https://github.com/chatwoot/chatwoot/assets/15706551/fcc87a7f-b3ef-4b48-956f-699ed53363e7)

Got to -> `app/models/concerns/message_filter_helpers.rd`
add
```
  def instagram?
    inbox.instagram?
  end
```
![image](https://github.com/chatwoot/chatwoot/assets/15706551/b80ae383-545b-4c91-82ce-5195aaa463da)

**Comment by sojan-official** [comment]
@DenisKarlyuk would you be interested in turning this into a pull request ? 😇

**Comment by DenisKarlyuk** [comment]
@sojan-official yep

**Comment by ultraza4** [comment]
> @DenisKarlyuk Thanks for share that solution, we modified this files, and work perfect. Now I'm sending app revision to facebook.


Please create a Pull Request, that would be very helpfull for everyone who is facing this problem.

**Comment by Elvner** [comment]
@pelucapampa  @sojan-official Has this issue been fixed? I tested it here and even so, after deleting the file, it remained in the chat. Only the adjustment made the goal approved even though the file was maintained?

**Comment by Elvner** [comment]
@DenisKarlyuk Thank you very much for your contribution! But when I tested the image continues to be stored by rails and displayed within chatwoot even after deletion, can you help please? I wanted to confirm whether even displaying it on the front is possible for approval.

**Comment by DenisKarlyuk** [comment]
@Elvner after the changes [above](https://github.com/chatwoot/chatwoot/issues/8512#issuecomment-1924124263) and restarting the chatwoot server the images should have the Instagram CDN url

**Comment by Elvner** [comment]
> @Elvner after the changes [above](https://github.com/chatwoot/chatwoot/issues/8512#issuecomment-1924124263) and restarting the chatwoot the images should have the Instagram CDN url
Would it be the network url or the HTML url that generates on the front? because on the front it has the rails link, and on the network too, would there be an ideal version for these adjustments to work?

**Comment by Elvner** [comment]
@DenisKarlyuk Would it be the network url or the HTML url that generates on the front? because on the front it has the rails link, and on the network too, would there be an ideal version for these adjustments to work?

**Comment by DenisKarlyuk** [comment]
@Elvner Sorry, I don't remember the version, but if you did everything correctly, it should work.

To pass Facebook revision, an Instagram message (regardless of message type: image or text) must be removed from the chatwoot if it has been deleted from Instagram and links to images must be in Instagram CDN format as in the [first message](https://github.com/chatwoot/chatwoot/issues/8512#issue-2030597523)

**Comment by rafaelstelles** [comment]
@DenisKarlyuk you are going to open a PR to fix the problem in chatwoot basecode ?

**Comment by DenisKarlyuk** [comment]
@rafaelstelles this is part of how it should be, this is just a hotfix for passing Facebook revision. I can't run chatwoot locally to continue.

**Comment by sojan-official** [comment]
note: added https://github.com/chatwoot/chatwoot/pull/9287/files with the changes from @DenisKarlyuk . We will test and get this merged

**Comment by tobsowo** [comment]
> Hi all. For those who can't wait: Go to -> `app/models/attachment.rd` change
> 
> ```
> metadata[:data_url] = metadata[:thumb_url] = external_url if message.instagram_story_mention?
> ```
> 
> to
> 
> ```
> metadata[:data_url] = metadata[:thumb_url] = external_url if message.instagram?
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/15706551/301894395-fcc87a7f-b3ef-4b48-956f-699ed53363e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjUwNzQsIm5iZiI6MTcxNTc2NDc3NCwicGF0aCI6Ii8xNTcwNjU1MS8zMDE4OTQzOTUtZmNjODdhN2YtYjNlZi00YjQ4LTk1NmYtNjk5ZWQ1MzM2M2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYTkxMTIyZjg2NDQyZGU1NWNmYjNmODg2N2I2MzViOGEwZjc3ZjUxZTFlYWNlMjU3MDQ3Mzc1NzEyNDhiNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ySw7VeyZo4u7-AyRpHdmoTEYbRY40efQD6j6s4WVuxk)
> 
> Go to -> `app/models/concerns/message_filter_helpers.rd` add
> 
> ```
>   def instagram?
>     inbox.instagram?
>   end
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/15706551/301894215-b80ae383-545b-4c91-82ce-5195aaa463da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjUwNzQsIm5iZiI6MTcxNTc2NDc3NCwicGF0aCI6Ii8xNTcwNjU1MS8zMDE4OTQyMTUtYjgwYWUzODMtNTQ1Yi00YzkxLTgyY2UtNTE5NWFhYTQ2M2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MDU0OTcwYmU4YTYxZWJhZDRiMmMyNDg2NjBiZDI1YzI0YjA0NDQ1YTlhOTU4MDgzZDMyZTM5NjNhYmM2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pJdQr_jUzQKNNuGjPurpw1aS2GeM_sDCH_bo4cwW4QU)

@DenisKarlyuk please how do I do this with a Docker installation?
I'll appreciate if you can guide.
Thank you.

**Comment by tobsowo** [comment]
> @tobsowo you should modify the files and than build the docker image using `docker-compose.yaml` at the root of the directory.

Please, how do I access the file after I gain access to the shell?
Will this also resolve auto deleting messages from IG and Chatwoot?

**Comment by DenisKarlyuk** [comment]
@tobsowo
1. Clone Chatwoot repository -> Change the files according to the instructions [above](https://github.com/chatwoot/chatwoot/issues/8512#issuecomment-1924124263) -> Build the docker image using `docker-compose.yaml`
2. Yes

**Comment by tobsowo** [comment]
@DenisKarlyuk I just updated to v3.9 and it does not delete messages although this fix is merged into it.
@sojan-official response here https://github.com/orgs/chatwoot/discussions/9479#discussioncomment-9454013
